CREATE TABLE IF NOT EXISTS shoes (
    id SERIAL PRIMARY KEY,
    brand VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    color VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL
);

INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Alphafly', 'Men''s Road Racing Shoes', 'Scream Green/Bright Crimson/Honeydew/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/c24ddc33-6e38-4cc9-b548-dc48cd3528ea/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Alphafly', 'Men''s Road Racing Shoes', 'Scream Green/Bright Crimson/Honeydew/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/c24ddc33-6e38-4cc9-b548-dc48cd3528ea/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Alphafly', 'Men''s Road Racing Shoes', 'Total Orange/Bright Crimson/Ghost Green/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/928f082e-4b98-4fb5-9eb2-13929291857e/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'ZoomX Vaporfly', 'Men''s Road Racing Shoes', 'Scream Green/Bright Crimson/Honeydew/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/8368dcfc-a3dc-4cab-b069-766f837fc8a5/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'ZoomX Vaporfly', 'Men''s Road Racing Shoes', 'Scream Green/Bright Crimson/Honeydew/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/8368dcfc-a3dc-4cab-b069-766f837fc8a5/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'ZoomX Vaporfly', 'Men''s Road Racing Shoes', 'White/Coconut Milk/Ghost Green/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/7e42659a-107f-4d5d-bc6f-d5b582e21db0/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'ZoomX Vaporfly', 'Men''s Road Racing Shoes', 'White/Volt/Racer Blue/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/8e454021-19eb-4a64-8dd8-48c28b1c6643/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'ZoomX Vaporfly', 'Men''s Road Racing Shoes', 'Red Clay/Ghost Green/Phantom/Game Royal', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/c4af86e1-e273-49c7-a4b9-2f60a80046c9/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'ZoomX Vaporfly', 'Men''s Road Racing Shoes', 'Total Orange/Bright Crimson/White/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/d887ad59-dd77-425a-afa0-00666e311710/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Zoom Fly 5', 'Men''s Running Shoes', 'Scream Green/Honeydew/Coconut Milk/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/065a2e7d-62b9-40fe-948b-3f9eb0dea8b3/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Zoom Fly 5', 'Men''s Running Shoes', 'Scream Green/Honeydew/Coconut Milk/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/065a2e7d-62b9-40fe-948b-3f9eb0dea8b3/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Zoom Fly 5', 'Men''s Running Shoes', 'White/Racer Blue/Bright Crimson/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/741b1b39-4a28-451d-b144-c6d22121c739/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Zoom Fly 5', 'Men''s Running Shoes', 'Cerulean/Bright Spruce/Peach Cream/White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/ee18eb38-d735-4ce0-a3ac-6ca94f750027/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Zoom Fly 5', 'Men''s Running Shoes', 'Black/White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/4b2715fe-3d81-4177-9f60-74d79112cca7/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Zoom Fly 5', 'Men''s Running Shoes', 'Black/Sail/Ghost Green/White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/58c3e1a7-6328-483f-9f59-fae78a51f871/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Zoom Fly 5', 'Men''s Running Shoes', 'Total Orange/Bright Crimson/White/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/cdb4e7b0-7772-41aa-82c0-4306f53050b6/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Zoom Fly 5', 'Men''s Running Shoes', 'Black/Ale Brown/Racer Blue/Phantom', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/685257d9-3614-403b-abc0-10635b951d8e/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Zoom Fly 5', 'Men''s Running Shoes', 'Cargo Khaki/Yellow Strike/White/Glacier Blue', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/9096e636-795a-4045-ad32-221c60b93e13/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Zoom Fly 5', 'Men''s Running Shoes', 'Mint Foam/Ghost Green/Coconut Milk/Cave Purple', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/87bf5e39-899e-4fba-8749-4a367224e7d0/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Pegasus 39', 'Men''s Road Running Shoes', 'Scream Green/Coconut Milk/Honeydew/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/e03f8fa2-652d-4ef8-aa02-1d8b8bb0e018/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Pegasus 39', 'Men''s Road Running Shoes', 'Scream Green/Coconut Milk/Honeydew/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/e03f8fa2-652d-4ef8-aa02-1d8b8bb0e018/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Pegasus 39', 'Men''s Road Running Shoes', 'White/Summit White/Volt/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/d3cafd13-160c-41d7-ae22-a800b001d21d/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Pegasus 39', 'Men''s Road Running Shoes', 'Black/Thunder Blue/Citron Pulse/Hyper Royal', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/81ea5bb7-6f0e-4e6b-8c5b-76167d33b072/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Pegasus 39', 'Men''s Road Running Shoes', 'Black/Gym Red/Black/White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/3f778d32-48be-45f2-a741-7a984d7290a9/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Pegasus 39', 'Men''s Road Running Shoes', 'Black/Thunder Blue/Citron Pulse/Hyper Royal', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/00165b2b-d8cd-4702-a611-7954c4ac3b26/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Pegasus 39', 'Men''s Road Running Shoes', 'Black/Coconut Milk/Safety Orange/Alabaster', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/1739375d-5017-4879-bdb2-aba6178403ee/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Pegasus 39', 'Men''s Road Running Shoes', 'Summit White/White/Washed Teal/University Red', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/259224c9-9fd4-499d-94c6-3d91d30a08c2/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Pegasus 39', 'Men''s Road Running Shoes', 'Gorge Green/Team Orange/Phantom/Ale Brown', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/2eecc06d-5915-4651-9cc6-eca519f5c350/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Pegasus 39', 'Men''s Road Running Shoes', 'White/Racer Blue/Volt/Bright Crimson', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/787102b4-4e32-413a-a37f-5648bb17036b/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Pegasus 39', 'Men''s Road Running Shoes', 'Sequoia/Medium Olive/Oil Green/University Gold', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/654594a8-e53e-4d2d-8f80-19766aedbd5d/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Air Zoom Pegasus 39', 'Men''s Road Running Shoes', 'Pine Green/Black/White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/b7fbc346-e1dd-43c5-96cf-36315fe41682/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Anthracite/Black/Lilac/Metallic Pewter', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/5504e8de-5ea7-4118-90c2-39ee24d52158/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Anthracite/Black/Lilac/Metallic Pewter', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/5504e8de-5ea7-4118-90c2-39ee24d52158/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Particle Grey/Light Smoke Grey/Grey Fog/Off Noir', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/8f3cda35-d270-4508-8d18-bf51377f5768/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'White/Particle Grey/Smoke Grey/Grey Fog', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/f9d66f4c-413e-4a97-9e30-65407a87ba83/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Black/Anthracite/Vivid Sulfur/Chlorine Blue', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/ee707e38-a124-4809-a899-f5b46fb1310a/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Black/Dark Smoke Grey/White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/01fa2267-5cd3-47e0-8280-c117221b7c83/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Black/Dark Smoke Grey/White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/a96f62d4-b20a-4371-a660-38565bc4581b/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Racer Blue/Black/Anthracite/White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/4ecd28da-cfd4-4e01-92c3-ca1522fa3513/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Football Grey/Concord/Dark Beetroot/Bright Crimson', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/fc69f3a9-a1e9-4bc1-93f6-93b1eee380f1/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Light Orewood Brown/Sail/Barely Volt/Red Plum', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/f3484b28-7886-4146-a931-a6f9c3a9f50c/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Black/Ashen Slate/Cobalt Bliss/White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/2e786079-c767-4fd9-b55c-6ad81c38c530/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Black/Ashen Slate/Cobalt Bliss/White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/e77392ff-1c89-4f80-b7ee-e8832be3356e/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Black/Anthracite/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/726c1030-7f7b-42f6-966c-ff305463cd1b/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Barely Green/Mint Foam/Volt/Cave Purple', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/9a50da4b-eead-4330-8a03-05fa4957f765/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Bright Spruce/Valerian Blue/Cerulean/Light Crimson', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/8bb6250a-af23-4b73-bf8c-ded532982e12/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Bright Spruce/Valerian Blue/Cerulean/Light Crimson', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/4198d75c-dc9b-449c-a06f-7fa30ecc4a9a/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'White/Bright Crimson/Black/Total Orange', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/4429a535-2333-423d-9473-eb728ad603b7/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Pure Platinum/Mineral Slate/Bright Spruce/Total Orange', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/b5d338dd-58b5-4134-8951-692c89477116/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Men''s Road Running Shoes', 'Siren Red/Red Clay/Phantom/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/8b3be65e-eb8c-47b6-9813-1160a4400ec1/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Women''s Road Running Shoes', 'Phantom/Summit White/Cerulean/Psychic Purple', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/b4d33067-a39e-476d-ab68-063b87ccca00/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Women''s Road Running Shoes', 'Phantom/Summit White/Cerulean/Psychic Purple', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/b4d33067-a39e-476d-ab68-063b87ccca00/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Women''s Road Running Shoes', 'Black/Dark Smoke Grey/White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/ea4d0764-a96c-48d5-9d02-aaa5f4106b89/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Women''s Road Running Shoes', 'Pink Oxford/Light Soft Pink/Champagne/Summit White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/f89a59ee-b368-4978-94e0-70eda3ea0b3b/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Women''s Road Running Shoes', 'Peach Cream/Total Orange/Green Shock/Ghost Green', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/27bb5a58-0613-4cfe-b29c-b49b6bba4a5d/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Women''s Road Running Shoes', 'Black/Dark Smoke Grey/White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/fc033b38-7a14-4974-882c-bee163d9ae1c/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Women''s Road Running Shoes', 'Phantom/Summit White/Cerulean/Psychic Purple', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/2b61fb83-92db-47df-98c3-b5bf60c9bcf0/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Women''s Road Running Shoes', 'Dark Smoke Grey/Olive Grey/Metallic Silver/Metallic Copper', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/5c29f504-973c-4d68-9e66-977d3ff73f43/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Women''s Road Running Shoes', 'Black/Off Noir/Light Thistle/Yellow Ochre', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/aacece4d-dd82-4e94-8c82-c851e8e89802/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Women''s Road Running Shoes', 'Barely Green/Mint Foam/Volt/Cave Purple', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/ab47d082-1786-4411-ad89-cb621da4c189/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Women''s Road Running Shoes', 'Iris Whisper/Summit White/Light Madder Root/Madder Root', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/89a3c86c-2a5e-4fbe-ac92-5d1077d13182/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Pegasus 39', 'Women''s Road Running Shoes', 'White/Pure Platinum/Grey Fog/Metallic Silver', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/d6420cb8-3eb5-4fb8-ab0e-5676a75710cb/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Invincible Run 2', 'Men''s Road Running Shoes', 'Black/Summit White/Summit White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/69956b92-20ab-42b5-9a79-d571413ccef2/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Invincible Run 2', 'Men''s Road Running Shoes', 'Black/Summit White/Summit White', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/69956b92-20ab-42b5-9a79-d571413ccef2/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Invincible Run 2', 'Men''s Road Running Shoes', 'Iron Grey/Wolf Grey/Kumquat', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/9c5d8b8a-525a-4a21-8484-a6797974f76e/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Invincible Run 2', 'Men''s Road Running Shoes', 'Siren Red/Team Red/Green Strike/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/0ae61545-5159-46bc-80d7-375037502b06/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Invincible Run 2', 'Men''s Road Running Shoes', 'Team Orange/Gorge Green/Sail/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/905ab682-462c-47de-a9da-aa772fd691cc/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'Invincible Run 2', 'Men''s Road Running Shoes', 'White/University Blue/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/7f8648a9-6f79-41f4-93b0-07a9015d0bc2/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'ZoomX Invincible Run Flyknit 2', 'Women''s Road Running Shoes', 'Dark Marina Blue/Plum Fog/Light Marine/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/76e6dd8d-5a2e-435c-bd9b-294b2e929d95/image.jpg');
INSERT INTO shoes ("brand", "model", "description", "color", "image") VALUES ('Nike', 'ZoomX Invincible Run Flyknit 2', 'Women''s Road Running Shoes', 'Dark Marina Blue/Plum Fog/Light Marine/Black', 'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/76e6dd8d-5a2e-435c-bd9b-294b2e929d95/image.jpg');
