/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServerlessDriverRouteImport } from './routes/serverless-driver'
import { Route as PostgresJsRouteImport } from './routes/postgres-js'
import { Route as NodePostgresRouteImport } from './routes/node-postgres'
import { Route as IndexRouteImport } from './routes/index'

const ServerlessDriverRoute = ServerlessDriverRouteImport.update({
  id: '/serverless-driver',
  path: '/serverless-driver',
  getParentRoute: () => rootRouteImport,
} as any)
const PostgresJsRoute = PostgresJsRouteImport.update({
  id: '/postgres-js',
  path: '/postgres-js',
  getParentRoute: () => rootRouteImport,
} as any)
const NodePostgresRoute = NodePostgresRouteImport.update({
  id: '/node-postgres',
  path: '/node-postgres',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/node-postgres': typeof NodePostgresRoute
  '/postgres-js': typeof PostgresJsRoute
  '/serverless-driver': typeof ServerlessDriverRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/node-postgres': typeof NodePostgresRoute
  '/postgres-js': typeof PostgresJsRoute
  '/serverless-driver': typeof ServerlessDriverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/node-postgres': typeof NodePostgresRoute
  '/postgres-js': typeof PostgresJsRoute
  '/serverless-driver': typeof ServerlessDriverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/node-postgres' | '/postgres-js' | '/serverless-driver'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/node-postgres' | '/postgres-js' | '/serverless-driver'
  id:
    | '__root__'
    | '/'
    | '/node-postgres'
    | '/postgres-js'
    | '/serverless-driver'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NodePostgresRoute: typeof NodePostgresRoute
  PostgresJsRoute: typeof PostgresJsRoute
  ServerlessDriverRoute: typeof ServerlessDriverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/serverless-driver': {
      id: '/serverless-driver'
      path: '/serverless-driver'
      fullPath: '/serverless-driver'
      preLoaderRoute: typeof ServerlessDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postgres-js': {
      id: '/postgres-js'
      path: '/postgres-js'
      fullPath: '/postgres-js'
      preLoaderRoute: typeof PostgresJsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/node-postgres': {
      id: '/node-postgres'
      path: '/node-postgres'
      fullPath: '/node-postgres'
      preLoaderRoute: typeof NodePostgresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NodePostgresRoute: NodePostgresRoute,
  PostgresJsRoute: PostgresJsRoute,
  ServerlessDriverRoute: ServerlessDriverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
