CREATE TABLE "Elements_ext" (
  AtomicNumber INTEGER PRIMARY KEY,
  "Element" TEXT,
  Symbol TEXT,
  AtomicMass DECIMAL,
  NumberOfNeutrons INTEGER,
  NumberOfProtons INTEGER,
  NumberOfElectrons INTEGER,
  "Period" INTEGER,
  "Group" INTEGER,
  Phase TEXT,
  Radioactive BOOLEAN,
  "Natural" BOOLEAN,
  Metal BOOLEAN,
  Nonmetal BOOLEAN,
  Metalloid BOOLEAN,
  "Type" TEXT,
  AtomicRadius DECIMAL,
  Electronegativity DECIMAL,
  FirstIonization DECIMAL,
  Density DECIMAL,
  MeltingPoint DECIMAL,
  BoilingPoint DECIMAL,
  NumberOfIsotopes INTEGER,
  Discoverer TEXT,
  "Year" INTEGER,
  SpecificHeat DECIMAL,
  NumberOfShells INTEGER,
  NumberOfValence INTEGER
);